### ISSUE TITLE
Error: No such file or directory: 'configs/default.yaml (VSCode)

### ISSUE THREAD

**Issue by YuanZhijie** [zju3dv/manhattan_sdf#17]
When I try to replicate in VScode

[Running] python -u "f:\Code\Code04_0617_Manhattan-SDF\manhattan_sdf-1\run.py"
Traceback (most recent call last):
  File "f:\Code\Code04_0617_Manhattan-SDF\manhattan_sdf-1\run.py", line 1, in <module>
    from lib.config import args, cfg
  File "f:\Code\Code04_0617_Manhattan-SDF\manhattan_sdf-1\lib\config\__init__.py", line 1, in <module>
    from .config import cfg, args
  File "f:\Code\Code04_0617_Manhattan-SDF\manhattan_sdf-1\lib\config\config.py", line 105, in <module>
    cfg = make_cfg(args)
  File "f:\Code\Code04_0617_Manhattan-SDF\manhattan_sdf-1\lib\config\config.py", line 87, in make_cfg
    cfg.merge_from_file(args.cfg_file)
  File "f:\Code\Code04_0617_Manhattan-SDF\manhattan_sdf-1\lib\config\yacs.py", line 169, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/default.yaml'

How should I solve this problem？

**Comment by ghy0324** [comment]
Command line arguments are missed. Please refer to the [usage](https://github.com/zju3dv/manhattan_sdf#usage).
