### ISSUE TITLE
different mesh visual and some error by running Mesh extraction and Evaluation

### ISSUE THREAD

**Issue by Gotta-C** [zju3dv/manhattan_sdf#45]

**Comment by Gotta-C** [comment]
Loading dataset: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 465/465 [00:17<00:00, 27.31it/s]
Querying SDF: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 269/269 [00:21<00:00, 12.33it/s]
Refusing:   0%|                                                                                                                                                                                                   | 0/465 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 65, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 21, in run_mesh_extract
    mesh = refuse(mesh, data_loader)
  File "/ali-nas/AI-GPU/chenguote/loc/manhattan_sdf/lib/utils/mesh_utils.py", line 68, in refuse
    _, depth_pred = renderer(h, w, intrinsic, pose, mesh_opengl)
  File "/ali-nas/AI-GPU/chenguote/loc/manhattan_sdf/lib/utils/mesh_utils.py", line 29, in __call__
    return self.renderer.render(self.scene)  # , self.render_flags)
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/pyrender/offscreen.py", line 102, in render
    retval = self._renderer.render(scene, flags, seg_node_map)
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/pyrender/renderer.py", line 125, in render
    self._update_context(scene, flags)
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/pyrender/renderer.py", line 738, in _update_context
    p._add_to_context()
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/pyrender/primitive.py", line 324, in _add_to_context
    self._vaid = glGenVertexArrays(1)
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 401, in __call__
    if self.load():
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 390, in load
    error_checker = self.error_checker,
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 148, in constructFunction
    if (not is_core) and not self.checkExtension( extension ):
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 270, in checkExtension
    result = extensions.ExtensionQuerier.hasExtension( name )
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/extensions.py", line 98, in hasExtension
    result = registered( specifier )
  File "/data/guote/miniconda3/envs/manhattan/lib/python3.7/site-packages/OpenGL/extensions.py", line 105, in __call__
    if not specifier.startswith( self.prefix ):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
